/*
 * MunbynBLE.app's executable (built by scripts/install-ble-bridge.sh).
 *
 * macOS decides whether a process may use Bluetooth by looking at its
 * *responsible* process: that one's Info.plist must carry
 * NSBluetoothAlwaysUsageDescription, and the grant is stored for its bundle
 * (com.m0n01d.munbyn-ble-bridge). So this launcher must stay alive as the
 * app's process and run Python as a CHILD -- exec() would turn this process
 * into Python and the bundle identity would be gone. Children inherit this
 * process as their responsible process, so the bridge (python -m
 * munbyn.ble_bridge) gets MunbynBLE's Bluetooth permission.
 *
 * It posix_spawn()s  <python> -m <module> [argv[1..]]  in <workdir>, forwards
 * SIGTERM/SIGINT/SIGHUP to the child (launchctl bootout / kickstart -k send
 * SIGTERM), and exits with the child's status (128+signal if it was killed).
 *
 * Paths come from launcher_config.h, generated by the installer:
 *   MUNBYN_PYTHON   the venv's python
 *   MUNBYN_WORKDIR  directory holding the munbyn package (cwd, so -m finds it)
 *   MUNBYN_MODULE   "munbyn.ble_bridge"
 * The environment variable MUNBYN_BLE_LAUNCHER_MODULE overrides the module;
 * it exists so the installer's dry run can check the launcher with a stub
 * module that never touches Bluetooth. The LaunchAgent never sets it.
 */
#include <errno.h>
#include <signal.h>
#include <spawn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>

#include "launcher_config.h"

extern char **environ;

static volatile sig_atomic_t child_pid = 0;

static void forward_signal(int sig) {
  pid_t pid = (pid_t)child_pid;
  if (pid > 0) kill(pid, sig);
}

int main(int argc, char **argv) {
  static const int forwarded[] = {SIGTERM, SIGINT, SIGHUP};
  const char *module = getenv("MUNBYN_BLE_LAUNCHER_MODULE");
  if (module == NULL || module[0] == '\0') module = MUNBYN_MODULE;

  if (chdir(MUNBYN_WORKDIR) != 0) {
    fprintf(stderr, "MunbynBLE: cannot enter %s: %s (re-run scripts/install-ble-bridge.sh)\n",
            MUNBYN_WORKDIR, strerror(errno));
    return 78; /* EX_CONFIG */
  }

  /* Block the forwarded signals until the child's pid is known, so one that
   * arrives in between is delivered (and forwarded) right after, not lost. */
  sigset_t block, old;
  sigemptyset(&block);
  for (size_t i = 0; i < sizeof forwarded / sizeof forwarded[0]; i++) sigaddset(&block, forwarded[i]);
  sigprocmask(SIG_BLOCK, &block, &old);

  struct sigaction sa;
  memset(&sa, 0, sizeof sa);
  sa.sa_handler = forward_signal;
  sigemptyset(&sa.sa_mask);
  sa.sa_flags = SA_RESTART;
  for (size_t i = 0; i < sizeof forwarded / sizeof forwarded[0]; i++) sigaction(forwarded[i], &sa, NULL);

  /* The child starts with default handlers and an empty mask. */
  posix_spawnattr_t attr;
  posix_spawnattr_init(&attr);
  sigset_t none, defaults;
  sigemptyset(&none);
  sigemptyset(&defaults);
  for (size_t i = 0; i < sizeof forwarded / sizeof forwarded[0]; i++) sigaddset(&defaults, forwarded[i]);
  posix_spawnattr_setsigmask(&attr, &none);
  posix_spawnattr_setsigdefault(&attr, &defaults);
  posix_spawnattr_setflags(&attr, POSIX_SPAWN_SETSIGMASK | POSIX_SPAWN_SETSIGDEF);

  char **args = calloc((size_t)argc + 4, sizeof(char *));
  if (args == NULL) return 71; /* EX_OSERR */
  int n = 0;
  args[n++] = (char *)MUNBYN_PYTHON;
  args[n++] = "-m";
  args[n++] = (char *)module;
  for (int i = 1; i < argc; i++) args[n++] = argv[i];
  args[n] = NULL;

  pid_t pid;
  int rc = posix_spawn(&pid, MUNBYN_PYTHON, NULL, &attr, args, environ);
  posix_spawnattr_destroy(&attr);
  if (rc != 0) {
    fprintf(stderr, "MunbynBLE: cannot start %s: %s (re-run scripts/install-ble-bridge.sh)\n", MUNBYN_PYTHON,
            strerror(rc));
    return 69; /* EX_UNAVAILABLE */
  }
  child_pid = pid;
  sigprocmask(SIG_SETMASK, &old, NULL);

  int status = 0;
  while (waitpid(pid, &status, 0) < 0) {
    if (errno != EINTR) {
      perror("MunbynBLE: waitpid");
      return 71;
    }
  }
  if (WIFEXITED(status)) return WEXITSTATUS(status);
  if (WIFSIGNALED(status)) {
    int sig = WTERMSIG(status);
    /* Goes to ~/Library/Logs/munbyn-ble-bridge.launchd.log. A bare SIGABRT
     * with no Python traceback above it (nothing logged by the bridge
     * itself) is what a TCC kill looks like: macOS aborts a process that
     * touches Bluetooth without NSBluetoothAlwaysUsageDescription, and
     * Python never gets to run an exception handler for it. */
    fprintf(stderr, "MunbynBLE: bridge (pid %d) killed by signal %d (%s)%s\n", (int)pid, sig, strsignal(sig),
            sig == SIGABRT ? ": possibly macOS TCC (Bluetooth privacy) -- see CLAUDE.md's TCC note" : "");
    return 128 + sig;
  }
  return 1;
}
