#!/usr/bin/env bash
# Installs (or removes) a macOS "PDF Service" menu item -- "Print to Munbyn
# RW403B" -- that appears in the print dialog's PDF dropdown and sends the
# document straight to print_label.py.
#
# CAVEAT (see PLANS/PLAN.md): executable ~/Library/PDF Services scripts have
# been reported broken since macOS Big Sur (the print dialog's host process
# is sandboxed and refuses to run scripts/binaries/Automator plugins). No
# first-hand confirmation either way was found for macOS 15/26. Test it
# before relying on it.
#
# Usage:
#   scripts/install-pdf-service.sh              # install
#   scripts/install-pdf-service.sh --uninstall  # remove
#
# Idempotent: re-running install overwrites the same generated file.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_NAME="Print to Munbyn RW403B"
SERVICE_DIR="$HOME/Library/PDF Services"
SERVICE_PATH="$SERVICE_DIR/$SERVICE_NAME"
LOG_PATH="$HOME/Library/Logs/munbyn-print.log"
VENV_PYTHON="$REPO_DIR/.venv/bin/python"
PRINT_SCRIPT="$REPO_DIR/print_label.py"

if [ "${1:-}" = "--uninstall" ]; then
  if [ -e "$SERVICE_PATH" ]; then
    rm -f "$SERVICE_PATH"
    echo "Removed: $SERVICE_PATH"
  else
    echo "Not installed ($SERVICE_PATH not found)."
  fi
  exit 0
fi

mkdir -p "$SERVICE_DIR"
mkdir -p "$(dirname "$LOG_PATH")"

cat > "$SERVICE_PATH" <<EOF
#!/bin/bash
# Auto-generated by scripts/install-pdf-service.sh -- edit that script, not
# this file (re-running it regenerates this one).
#
# macOS invokes a PDF Service with the document title and various CUPS/print
# options as leading arguments and the spooled PDF's path as the LAST
# argument. Apple does not formally document this argv contract, so we
# defensively scan all arguments and use the last one that is a readable
# file, rather than assuming a fixed position.
LOG="$LOG_PATH"

pdf=""
for arg in "\$@"; do
  if [ -f "\$arg" ]; then
    pdf="\$arg"
  fi
done

{
  echo "\$(date '+%Y-%m-%d %H:%M:%S') invoked with: \$*"
} >> "\$LOG"

notify() {
  osascript -e "display notification \\"\$2\\" with title \\"Munbyn RW403B\\" subtitle \\"\$1\\"" >/dev/null 2>&1 || true
}

if [ -z "\$pdf" ]; then
  echo "\$(date '+%Y-%m-%d %H:%M:%S') error: no readable PDF argument found" >> "\$LOG"
  notify "Print failed" "No PDF file was received."
  exit 1
fi

if "$VENV_PYTHON" "$PRINT_SCRIPT" --crop none --fit fit --rotate auto "\$pdf" >> "\$LOG" 2>&1; then
  echo "\$(date '+%Y-%m-%d %H:%M:%S') printed: \$pdf" >> "\$LOG"
  notify "Print sent" "Sent to the Munbyn RW403B."
  exit 0
else
  status=\$?
  echo "\$(date '+%Y-%m-%d %H:%M:%S') print_label.py exited \$status for: \$pdf" >> "\$LOG"
  notify "Print failed" "print_label.py failed -- see ~/Library/Logs/munbyn-print.log"
  exit "\$status"
fi
EOF

chmod +x "$SERVICE_PATH"

echo "Installed: $SERVICE_PATH"
echo "It should appear in the macOS print dialog's PDF dropdown as \"$SERVICE_NAME\"."
echo "Log: $LOG_PATH"
echo
echo "Caveat: executable PDF Services are reported broken on macOS since Big Sur"
echo "(print-dialog sandboxing). Test with a real Print dialog before relying on it"
echo "-- see PLANS/PLAN.md for the research and fallback options."
